version: "3"
services:
  jib-example:
    image: "dazzbourgh/jib-example:${JIB_BRANCH}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend=jib-example"
        - "traefik.frontend.rule=PathPrefixStrip:/jib-example-${JIB_BRANCH}"
        - "traefik.port=1489"

# created on the cluster beforehand
networks:
  default:
    external:
      name: traefik-net