version: "3"
services:
  jib-example:
    image: dazzbourgh/jib-example:latest
    ports:
      - "1489"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:whoami.docker.localhost"

# created on the cluster beforehand
networks:
  default:
    external:
      name: traefik-net