version: "3"
services:
  jib-example:
    image: dazzbourgh/jib-example:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend=jib-example"
        - "traefik.frontend.rule=PathPrefixStrip:/jib-example"
        - "traefik.port=80"

# created on the cluster beforehand
networks:
  default:
    external:
      name: traefik-net