version: "3"
services:
  jib-example:
    image: dazzbourgh/jib-example:latest
    ports:
      - "1489"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

# created on the cluster beforehand
networks:
  default:
    external:
      name: traefik-net