version: '3'

services:
  traefik:
    image: traefik # The official Traefik docker image
    # Enables the web UI and tells Traefik to listen to docker
    command: --api --docker --docker.swarmmode --docker.watch --logLevel=DEBUG --web
    ports:
      - "80:80"     # The HTTP port
      - "8081:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  default:
    external:
      name: traefik-net